{
  "class": "vulnerability",
  "id": "oval:com.ubuntu.bionic:def:2019209160000000",
  "version": "1",
  "metadata": {
    "Title": "CVE-2019-20916 on Ubuntu 18.04 LTS (bionic) - medium.",
    "Description": "The pip package before 19.2 for Python allows Directory Traversal when a URL is given in an install command, because a Content-Disposition header can have ../ in a filename, as demonstrated by overwriting the /root/.ssh/authorized_keys file. This occurs in _download_http_url in _internal/download.py.\n\nUpdate Instructions:\n\nRun `sudo pro fix CVE-2019-20916` to fix the vulnerability. The problem can be corrected\nby updating your system to the following package versions:\n\npython-pip - 9.0.1-2.3~ubuntu1.18.04.4\npython-pip-whl - 9.0.1-2.3~ubuntu1.18.04.4\npython3-pip - 9.0.1-2.3~ubuntu1.18.04.4\nNo subscription required",
    "affected": {
      "family": "unix",
      "Platform": "Ubuntu 18.04 LTS"
    },
    "reference": {
      "source": "CVE",
      "ref_id": "CVE-2019-20916",
      "ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-20916"
    },
    "advisory": {
      "Severity": "Medium",
      "Rights": "Copyright (C) 2020 Canonical Ltd.",
      "PublicDate": "2020-09-04 20:15:00 UTC",
      "Bug": null,
      "cve": {
        "text": "CVE-2019-20916",
        "href": "https://ubuntu.com/security/CVE-2019-20916",
        "public": "20200904",
        "cvss_score": "7.5",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
        "usns": "4601-1"
      },
      "PublicDateAtUsn": "2020-09-04 20:15:00 UTC",
      "AssignedTo": "",
      "DiscoveredBy": "",
      "Crd": "",
      "Ref": null
    }
  },
  "notes": {
    "Note": ""
  },
  "criteria": {
    "criterions": [
      {
        "test_ref": "oval:com.ubuntu.bionic:tst:2019209160000000",
        "comment": "python-pip package in bionic was vulnerable but has been fixed (note: '9.0.1-2.3~ubuntu1.18.04.4')."
      }
    ]
  }
}
