{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.bionic:def:2023466950000000",
	"version": "1",
	"metadata": {
		"title": "CVE-2023-46695 on Ubuntu 18.04 LTS (bionic) - medium",
		"description": "An issue was discovered in Django 3.2 before 3.2.23, 4.1 before 4.1.13, and4.2 before 4.2.7. The NFKC normalization is slow on Windows. As aconsequence, django.contrib.auth.forms.UsernameField is subject to apotential DoS (denial of service) attack via certain inputs with a verylarge number of Unicode characters.",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 18.04 LTS"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2023-46695",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-46695"
		},
		"advisory": {
			"severity": "Medium",
			"rights": "Copyright (C) 2023 Canonical Ltd.",
			"public_date": "2023-11-02 06:15:00 UTC",
			"cve": {
				"text": "CVE-2023-46695",
				"href": "https://ubuntu.com/security/CVE-2023-46695",
				"public": "20231102",
				"cvss_score": "7.5",
				"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
			}
		}
	},
	"notes": {},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.bionic:tst:2023360530000000",
						"comment": "python-django: while related to the CVE in some way, a decision has been made to ignore this issue (note: 'end of standard support')."
					}
				]
			}
		]
	}
}
