{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.focal:def:2021212390000000",
	"version": "1",
	"metadata": {
		"title": "CVE-2021-21239 on Ubuntu 20.04 FIPS Certified (focal) - medium",
		"description": "PySAML2 is a pure python implementation of SAML Version 2 Standard. PySAML2before 6.5.0 has an improper verification of cryptographic signaturevulnerability. Users of pysaml2 that use the default CryptoBackendXmlSec1backend and need to verify signed SAML documents are impacted. PySAML2 doesnot ensure that a signed SAML document is correctly signed. The defaultCryptoBackendXmlSec1 backend is using the xmlsec1 binary to verify thesignature of signed SAML documents, but by default xmlsec1 accepts any typeof key found within the given document. xmlsec1 needs to be configuredexplicitly to only use only _x509 certificates_ for the verificationprocess of the SAML document signature. This is fixed in PySAML2 6.5.0.\n\n    Update Instructions:\n\n    Run `sudo pro fix CVE-2021-21239` to fix the vulnerability. The problem can be corrected\n    by updating your system to the following package versions:\n\npython3-pysaml2 - 4.9.0-0ubuntu3.1\nNo subscription required",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 20.04 FIPS Certified"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2021-21239",
			"ref_url": "https://www.cve.org/CVERecord?id=CVE-2021-21239"
		},
		"advisory": {
			"severity": "Medium",
			"rights": "Copyright (C) 2021 Canonical Ltd.",
			"public_date": "2021-01-21 15:15:00 UTC",
			"bug": [
				"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980772"
			],
			"cve": {
				"text": "CVE-2021-21239",
				"href": "https://ubuntu.com/security/CVE-2021-21239",
				"public": "20210121",
				"cvss_score": "6.5",
				"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
				"usns": "5066-1,5066-2"
			},
			"public_date_at_usn": "2021-01-21 15:15:00 UTC",
			"assigned_to": "mdeslaur",
			"ref": [
				"https://ubuntu.com/security/notices/USN-5066-1",
				"https://ubuntu.com/security/notices/USN-5066-2"
			]
		}
	},
	"notes": {},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.focal:tst:2021212390000000",
						"comment": "python-pysaml2 package in focal was vulnerable but has been fixed (note: '4.9.0-0ubuntu3.1')."
					}
				]
			}
		]
	}
}
