{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.xenial:def:2019148580000000",
	"version": "1",
	"metadata": {
		"Title": "CVE-2019-14858 on Ubuntu 16.04 LTS (xenial) - low.",
		"Description": "A vulnerability was found in Ansible engine 2.x up to 2.8 and Ansible tower 3.x up to 3.5. When a module has an argument_spec with sub parameters marked as no_log, passing an invalid parameter name to the module will cause the task to fail before the no_log options in the sub parameters are processed. As a result, data in the sub parameter fields will not be masked and will be displayed if Ansible is run with increased verbosity and present in the module invocation arguments for the task.",
		"affected": {
			"family": "unix",
			"Platform": "Ubuntu 16.04 LTS"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2019-14858",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14858"
		},
		"advisory": {
			"Severity": "Low",
			"Rights": "Copyright (C) 2019 Canonical Ltd.",
			"PublicDate": "2019-10-14 15:15:00 UTC",
			"Bug": null,
			"cve": {
				"text": "CVE-2019-14858",
				"href": "https://ubuntu.com/security/CVE-2019-14858",
				"public": "20191014",
				"cvss_score": "5.5",
				"cvss_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
			},
			"PublicDateAtUsn": "",
			"AssignedTo": "",
			"DiscoveredBy": "",
			"Crd": "",
			"Ref": null
		}
	},
	"notes": {
		"Note": ""
	},
	"criteria": {
		"criterions": [
			{
				"test_ref": "oval:com.ubuntu.xenial:tst:201686140000000",
				"comment": "ansible: while related to the CVE in some way, a decision has been made to ignore this issue (note: 'end of standard support, was needs-triage')."
			}
		]
	}
}
