{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.hirsute:def:2021400830000000",
	"version": "1",
	"metadata": {
		"title": "CVE-2021-40083 on Ubuntu 21.04 (hirsute) - medium.",
		"description": "Knot Resolver before 5.3.2 is prone to an assertion failure, triggerable by a remote attacker in an edge case (NSEC3 with too many iterations used for a positive wildcard proof).",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 21.04"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2021-40083",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-40083"
		},
		"advisory": {
			"severity": "Medium",
			"rights": "Copyright (C) 2021 Canonical Ltd.",
			"public_date": "2021-08-25 01:15:00 UTC",
			"bug": [
				"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=991463"
			],
			"cve": {},
			"ref": [
				"http://people.canonical.com/~ubuntu-security/cve/2021/CVE-2021-40083.html",
				"https://gitlab.nic.cz/knot/knot-resolver/-/merge_requests/1169"
			]
		}
	},
	"notes": {},
	"criteria": {
		"criterions": [
			{
				"test_ref": "oval:com.ubuntu.hirsute:tst:2018109200000000",
				"comment": "knot-resolver package in hirsute is affected and may need fixing."
			}
		]
	}
}
