{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.hirsute:def:201679460000000",
	"version": "1",
	"metadata": {
		"Title": "CVE-2016-7946 on Ubuntu 21.04 (hirsute) - low.",
		"Description": "X.org libXi before 1.7.7 allows remote X servers to cause a denial of service (infinite loop) via vectors involving length fields.",
		"affected": {
			"family": "unix",
			"Platform": "Ubuntu 21.04"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2016-7946",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-7946"
		},
		"advisory": {
			"Severity": "Low",
			"Rights": "Copyright (C) 2016 Canonical Ltd.",
			"PublicDate": "2016-12-13 20:59:00 UTC",
			"Bug": [
				"https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840440"
			],
			"cve": {},
			"PublicDateAtUsn": "",
			"AssignedTo": "",
			"DiscoveredBy": "Tobias Stoeckmann",
			"Crd": "",
			"Ref": [
				"http://people.canonical.com/~ubuntu-security/cve/2016/CVE-2016-7946.html",
				"http://www.openwall.com/lists/oss-security/2016/10/04/4",
				"https://lists.x.org/archives/xorg-announce/2016-October/002720.html"
			]
		}
	},
	"notes": {
		"Note": "sbeattie> same commit as CVE-2016-7945 mdeslaur> possible regression: https://bugs.freedesktop.org/show_bug.cgi?id=98204"
	},
	"criteria": {
		"criterions": [
			{
				"test_ref": "oval:com.ubuntu.hirsute:tst:201679450000000",
				"comment": "libxi package in hirsute, is related to the CVE in some way and has been fixed (note: '2:1.7.8-1')."
			}
		]
	}
}
