{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.hirsute:def:2020261480000000",
	"version": "1",
	"metadata": {
		"Title": "CVE-2020-26148 on Ubuntu 21.04 (hirsute) - medium.",
		"Description": "md_push_block_bytes in md4c.c in md4c 0.4.5 allows attackers to trigger use of uninitialized memory, and cause a denial of service (e.g., assertion failure) via a malformed Markdown document.",
		"affected": {
			"family": "unix",
			"Platform": "Ubuntu 21.04"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2020-26148",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-26148"
		},
		"advisory": {
			"Severity": "Medium",
			"Rights": "Copyright (C) 2020 Canonical Ltd.",
			"PublicDate": "2020-09-30 18:15:00 UTC",
			"Bug": [
				"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=971396"
			],
			"cve": {},
			"PublicDateAtUsn": "",
			"AssignedTo": "",
			"DiscoveredBy": "",
			"Crd": "",
			"Ref": [
				"http://people.canonical.com/~ubuntu-security/cve/2020/CVE-2020-26148.html",
				"https://github.com/mity/md4c/issues/130",
				"https://github.com/mity/md4c/commit/22ca89a3008966c4316d6b0a158b1a49f9038df0"
			]
		}
	},
	"notes": {
		"Note": ""
	},
	"criteria": {
		"criterions": [
			{
				"test_ref": "oval:com.ubuntu.hirsute:tst:2020261480000000",
				"comment": "md4c package in hirsute is affected and may need fixing."
			}
		]
	}
}
