{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.trusty:def:2019199110000000",
	"version": "1",
	"metadata": {
		"Title": "CVE-2019-19911 on Ubuntu 14.04 LTS (trusty) - low",
		"Description": "There is a DoS vulnerability in Pillow before 6.2.2 caused byFpxImagePlugin.py calling the range function on an unvalidated 32-bitinteger if the number of bands is large. On Windows running 32-bit Python,this results in an OverflowError or MemoryError due to the 2 GB limit.However, on Linux running 64-bit Python this results in the process beingterminated by the OOM killer.",
		"affected": {
			"family": "unix",
			"Platform": "Ubuntu 14.04 LTS"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2019-19911",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-19911"
		},
		"advisory": {
			"Severity": "Low",
			"Rights": "Copyright (C) 2020 Canonical Ltd.",
			"PublicDate": "2020-01-05 22:15:00 UTC",
			"Bug": [
				"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=948224"
			],
			"cve": {
				"text": "CVE-2019-19911",
				"href": "https://ubuntu.com/security/CVE-2019-19911",
				"public": "20200105",
				"cvss_score": "7.5",
				"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
				"usns": "4272-1"
			},
			"PublicDateAtUsn": "2020-01-05 22:15:00 UTC",
			"AssignedTo": "",
			"DiscoveredBy": "",
			"Crd": "",
			"Ref": [
				"https://ubuntu.com/security/notices/USN-4272-1"
			]
		}
	},
	"notes": {
		"Note": ""
	},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.trusty:tst:2019168650000000",
						"comment": "pillow: while related to the CVE in some way, a decision has been made to ignore this issue (note: 'end of standard support')."
					}
				]
			}
		]
	}
}
