{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.noble:def:201975480000000",
	"version": "1",
	"metadata": {
		"title": "CVE-2019-7548 on Ubuntu 24.04 LTS (noble) - low",
		"description": "SQLAlchemy 1.2.17 has SQL Injection when the group_by parameter can becontrolled.\n\n    Update Instructions:\n\n    Run `sudo pro fix CVE-2019-7548` to fix the vulnerability. The problem can be corrected\n    by updating your system to the following package versions:\n\npython3-sqlalchemy - 1.2.18+ds1-2ubuntu1\npython3-sqlalchemy-ext - 1.2.18+ds1-2ubuntu1\nNo subscription required",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 24.04 LTS"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2019-7548",
			"ref_url": "https://www.cve.org/CVERecord?id=CVE-2019-7548"
		},
		"advisory": {
			"severity": "Low",
			"rights": "Copyright (C) 2019 Canonical Ltd.",
			"public_date": "2019-02-06 21:29:00 UTC",
			"bug": [
				"https://github.com/sqlalchemy/sqlalchemy/issues/4481#issuecomment-461204518"
			],
			"cve": {
				"text": "CVE-2019-7548",
				"href": "https://ubuntu.com/security/CVE-2019-7548",
				"public": "20190206",
				"cvss_score": "7.8",
				"cvss_vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
			}
		}
	},
	"notes": {},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.noble:tst:201971640000000",
						"comment": "sqlalchemy package in noble, is related to the CVE in some way and has been fixed (note: '1.2.18+ds1-2ubuntu1')."
					}
				]
			}
		]
	}
}
